<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>Properties\EverybodyCodes.snk</AssemblyOriginatorKeyFile>
    <Configurations>Release;Debug</Configurations>
    <Platforms>x64</Platforms>
    <ApplicationIcon>Assets\ec.ico</ApplicationIcon>
  </PropertyGroup>

  <PropertyGroup>
    <BuildYear>$([System.DateTime]::UtcNow.ToString("yyyy"))</BuildYear>
    <BuildMonth>$([System.DateTime]::UtcNow.ToString("MM"))</BuildMonth>
    <MonthStart>$([System.DateTime]::Parse($([System.DateTime]::UtcNow.ToString("yyyy-MM-01"))))</MonthStart>
    <MonthMinutes>$([System.Math]::Floor($([System.DateTime]::UtcNow.Subtract($(MonthStart)).TotalMinutes)))</MonthMinutes>
    <DaySeconds>$([System.Math]::Floor($([System.DateTime]::UtcNow.Subtract($([System.DateTime]::Today)).TotalMinutes)))</DaySeconds>
    <Version>$(BuildYear).$(BuildMonth).$(MonthMinutes).$(DaySeconds)</Version>
    <AssemblyVersion>$(Version)</AssemblyVersion>
    <FileVersion>$(Version)</FileVersion>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x64' ">
    <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x64' ">
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" />
    <PackageReference Include="JetBrains.ExternalAnnotations" Version="10.2.170" />
    <PackageReference Include="Refit" Version="16.1.0" />
    <PackageReference Include="Refit.HttpClientFactory" Version="16.1.0" />
    <PackageReference Include="Refit.Reflection" Version="16.1.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EverybodyCodes.Resolver\EverybodyCodes.Resolver.csproj" />
    <ProjectReference Include="..\Libraries\Challenge.CLI\Challenge.CLI.csproj" />
    <ProjectReference Include="..\Libraries\Challenge.Generator\Challenge.Generator.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="EverybodyCodes.csproj.DotSettings" />
  </ItemGroup>

</Project>
