<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <AssemblyVersion>2026.1.0</AssemblyVersion>
    <FileVersion>2026.1.0</FileVersion>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>Properties\EverybodyCodes.snk</AssemblyOriginatorKeyFile>
    <Configurations>Release;Debug</Configurations>
    <Platforms>x64</Platforms>
    <ApplicationIcon>Assets\ec.ico</ApplicationIcon>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x64' ">
    <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x64' ">
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="EverybodyCodes.csproj.DotSettings" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" />
    <PackageReference Include="JetBrains.ExternalAnnotations" Version="10.2.170" />
  </ItemGroup>

</Project>
